version: '3.9'

services:
  app:
    container_name: Core
    build:
      context: docker/conf/core
      args:
        PHP_VERSION: ${PHP_VERSION:-8.2}
        UID: ${UID:-1000}
        SERVER_DOMAIN: ${SERVER_DOMAIN:-localhost}
    restart: always
    env_file:
      - "./.env"
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./../application:/var/www/html
      - ./docker/conf/php/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ./docker/conf/php/openssl.cnf:/etc/ssl/openssl.cnf
      - ./docker/conf/ssl:/etc/apache2/ssl:rw
      - ./docker/logs/apache:/var/log/apache2
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - abmmhasan-net

networks:
  abmmhasan-net:
    driver: bridge
