version: '3.9'

services:
    app:
      container_name: Core
      build:
        context: docker/conf/core
        args:
            PHP_VERSION: ${PHP_VERSION:-8.2}
            UID: ${UID:-1000}
            SERVER_DOMAIN: ${SERVER_DOMAIN:-localhost}
      env_file:
        - "./.env"
      ports:
        - "${HTTP_PORT:-80}:80"
        - "${HTTPS_PORT:-443}:443"
      volumes:
        - ./../application:/var/www/html
        - ./docker/conf/core/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
        - ./docker/conf/core/openssl.cnf:/etc/ssl/openssl.cnf
        - ./docker/conf/ssl:/etc/apache2/ssl
        - ./docker/logs/apache:/var/log/apache2
      extra_hosts:
        - 'host.docker.internal:host-gateway'
      networks:
        - abmmhasan-net

    mysql:
      container_name: MYSQL
      image: mysql:${MYSQL_VERSION:-latest}
      restart: always
      ports:
        - "${MYSQL_PORT:-3306}:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - TZ=${TZ:-Asia/Dhaka}
      volumes:
        - ./docker/data/mysql:/var/lib/mysql
        - ./docker/logs/mysql:/var/log/mysql
      networks:
        - abmmhasan-net

    phpmyadmin:
      container_name: MYADMIN
      image: phpmyadmin:latest
      restart: always
      ports:
        - "${MYADMIN_PORT:-3050}:80"
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
        - PMA_PORT=${MYSQL_PORT:-3306}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      volumes:
        - ./docker/conf/core/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      depends_on:
        - mysql
      networks:
        - abmmhasan-net

    postgres:
      container_name: POSTGRESQL
      image: postgres:${POSTGRESQL_VERSION:-latest}
      restart: always
      ports:
        - "${POSTGRESQL_PORT:-5432}:5432"
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DATABASE}
        - TZ=${TZ:-Asia/Dhaka}
      volumes:
        - ./docker/data/postgresql:/var/lib/postgresql
      networks:
        - abmmhasan-net

    pgadmin:
      container_name: PGADMIN
      image: dpage/pgadmin4:latest
      restart: always
      ports:
        - "${PGADMIN_PORT:-5050}:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@email.com
        PGADMIN_DEFAULT_PASSWORD: admin
      volumes:
        - ./data/pgadmin-data:/var/lib/pgadmin
      depends_on:
        - postgres
      networks:
        - abmmhasan-net

networks:
  abmmhasan-net:
    driver: bridge