version: '3.9'

services:
    mysql:
      container_name: MYSQL
      image: mysql:${MYSQL_VERSION:-latest}
      restart: always
      ports:
        - "${MYSQL_PORT:-3306}:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - TZ=${TZ:-Asia/Dhaka}
      volumes:
        - ./docker/data/mysql-data:/var/lib/mysql
      networks:
        - abmmhasan-net
    
    phpmyadmin:
      container_name: MYADMIN
      image: phpmyadmin:latest
      restart: always
      ports:
        - "${MYADMIN_PORT:-3050}:80"
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
      volumes:
        - ./conf/core/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      depends_on:
        - mysql
      networks:
        - abmmhasan-net