version: '3.9'

services:
    postgres:
      container_name: POSTGRESQL
      image: postgres:${POSTGRESQL_VERSION:-latest}
      restart: always
      ports:
        - "${POSTGRESQL_PORT:-5432}:5432"
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DATABASE}
        - TZ=${TZ:-Asia/Dhaka}
      volumes:
        - ./data/postgresql-data:/var/lib/postgresql
      networks:
        - abmmhasan-net

    pgadmin:
      container_name: PGADMIN
      image: dpage/pgadmin4:latest
      restart: always
      ports:
        - "${PGADMIN_PORT:-5050}:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@email.com
        PGADMIN_DEFAULT_PASSWORD: admin
      volumes:
        - ./data/pgadmin-data:/var/lib/pgadmin
      depends_on:
        - postgres
      networks:
        - abmmhasan-net